### ISSUE TITLE
[search] Crafter Engine's Elasticsearch endpoint alters elastic response in some cases

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#3978]
## Describe the bug
Crafter Engine's Elasticsearch endpoint alters elastic response in some cases

## To Reproduce

For the steps below Issue the following query structure:
```
{
  "query": {
    "multi_match": {
      "query": "lorem",
      "fields": [
        ...
      ]
    }
  },
  "highlight": {
    "type": "unified",
    "force_source": true,
    "order": "score",
    "fields": {
      ...
    }
  }
```

1. Issue the query to elastic directly
```
hits.hits.highlight.SOME_FIELD: [
  "<em>Lorem</em> ipsum 1",
  "<em>Lorem</em> ipsum 2",
  "<em>Lorem</em> ipsum 3"
]
```

2.  issue the query to Crafter
```
hits.hits.highlightFields.SOME_FIELD.fragments: {
  {
    "fragment": true
  },
  {
    "fragment": true
  },
  {
    "fragment": true
  }
}
```

3. Note the difference in the result structure

## Expected behavior
Crafter's result structure should _MATCH_ elastics's result structure

## Screenshots
N/A

## Logs
N/A

### Version
Studio Version Number: 3.1.5E-78758b
Build Number: 78758bb3b0ef328184808e93e5f1aea7687262c5
Build Date/Time: 02-21-2020 18:38:13 -0500

### OS
Any

### Browser
All

## Tasks
- [x] Address issue
- [ ] Test commerce tools blueprint
- [ ] Test videocenter blueprint
- [x] Test wordify blueprint
- [x] Check documentation for examples and update if needed
- [x] Check SDK JS
- [ ] Docs
- [ ] Include notice in release notes

**Comment by jdrossl** [comment]
@rart I think for the blueprints the only change needed is replacing `hits.hits.sourceAsMap` for `hits.hits._source`, let me know if need any more details

**Comment by rart** [comment]
@russdanner please test as needed. make sure these PRs are merged or you pull from the respective PR branches to test.
https://github.com/craftercms/commercetools-blueprint/pull/10
https://github.com/craftercms/video-center-blueprint/pull/97

I marked `wordify` as complete on the TODO list above since it doesn't have search implemented yet so it's not a problem (unless the GraphQL guts haven't been updated accordingly @jdrossl)

@sumerjabri FYI UI work complete.

@jdrossl 
> @rart I think for the blueprints the only change needed is replacing `hits.hits.sourceAsMap` for `hits.hits._source`, let me know if need any more details
The other thing we found changed was `totalHits` => `total`


---- • ----
Note to devs:
Summary of changes to response
https://github.com/craftercms/docs/commit/5590739429774df7fffbe2d4767529549ec26176?diff=split

**Comment by sumerjabri** [comment]
@russdanner both blueprints have been published to the Crafter CMS Marketplace. They're now in review, once approved, we can make them public/live.

**Comment by russdanner** [comment]
Video center blueprint fails to render due to exception. See attached screen shot. 
Create site from marketplace -> see error.

```
react-dom.production.min.js:198 TypeError: Cannot read property 'content-type' of undefined
    at Cards.js:142
    at Array.map (<anonymous>)
    at n.value (Cards.js:140)
    at n.value (Cards.js:260)
    at Co (react-dom.production.min.js:173)
    at Eo (react-dom.production.min.js:172)
    at Po (react-dom.production.min.js:180)
    at Yc (react-dom.production.min.js:232)
    at Gc (react-dom.production.min.js:233)
    at ka (react-dom.production.min.js:249)
hostReportError.ts:8 Uncaught TypeError: Cannot read property 'content-type' of undefined
    at Cards.js:142
    at Array.map (<anonymous>)
    at n.value (Cards.js:140)
    at n.value (Cards.js:260)
    at Co (react-dom.production.min.js:173)
    at Eo (react-dom.production.min.js:172)
    at Po (react-dom.production.min.js:180)
    at Yc (react-dom.production.min.js:232)
    at Gc (react-dom.production.min.js:233)
    at ka (react-dom.production.min.js:249)
```

<img width="1679" alt="Screen Shot 2020-04-21 at 12 22 43 AM" src="https://user-images.githubusercontent.com/169432/79825502-2858cd80-8367-11ea-9f16-cc658b14081b.png">

**Comment by russdanner** [comment]
Commerce tools BP fails on search 
install blueprint -> search("dress") -> see error

```
﻿
react-dom.production.min.js:4408 TypeError: Cannot read property 'objectId' of undefined
    at VM726 3.9e533c83.chunk.js:1
    at Array.map (<anonymous>)
    at sn (VM726 3.9e533c83.chunk.js:1)
    at Xl (VM713 4.ffd567ed.chunk.js:1)
    at Ci (VM713 4.ffd567ed.chunk.js:1)
    at Mi (VM713 4.ffd567ed.chunk.js:1)
    at $a (VM713 4.ffd567ed.chunk.js:1)
    at Qa (VM713 4.ffd567ed.chunk.js:1)
    at Oo (VM713 4.ffd567ed.chunk.js:1)
    at Po (VM713 4.ffd567ed.chunk.js:1)
hostReportError.js:4 Uncaught TypeError: Cannot read property 'objectId' of undefined
    at VM726 3.9e533c83.chunk.js:1
    at Array.map (<anonymous>)
    at sn (VM726 3.9e533c83.chunk.js:1)
    at Xl (VM713 4.ffd567ed.chunk.js:1)
    at Ci (VM713 4.ffd567ed.chunk.js:1)
    at Mi (VM713 4.ffd567ed.chunk.js:1)
    at $a (VM713 4.ffd567ed.chunk.js:1)
    at Qa (VM713 4.ffd567ed.chunk.js:1)
    at Oo (VM713 4.ffd567ed.chunk.js:1)
    at Po (VM713 4.ffd567ed.chunk.js:1)
```

**Comment by rart** [comment]
@russdanner these look like the errors prior to the fixes. Please detail how you created the blueprints.

As I understand, your need to enable certain props somewhere and restart to create from marketplace and get the latest/unpublished. If you create from marketplace regularly, you’ll get the current versions which are as they’ve always been.

@jdrossl @sumerjabri can you elaborate?

**Comment by sumerjabri** [comment]
@russdanner please switch your Studio to allow unapproved items:

```
# Indicates if the search should include plugins pending of approval
studio.marketplace.search.pending: false
```

**Comment by sumerjabri** [comment]
Verified fixed.
