### ISSUE TITLE
[studio][engine][deployer] Multi-target configuration support

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4008]
**Is your feature request related to a problem? Please describe.**
In some cases, the configuration is not only different per environment, but also different per publishing target:
* Preview
* Staging
* Live

Consider different SAML authentication mechanics per target or different URL rewrites per target within the same environment. For a concrete example, consider:
* Production Environment > Staging Target > SAML authentication IdP

**Describe the solution you'd like**
We need to support a base configuration per environment with the ability to override per target. We would use the convention:
`CONFIGURATION-FILE-NAME.{target}.xml`

Where `{target}` is one of:
* preview
* staging
* live

If the target is not present, the configuration system will load:
`CONFIGURATION-FILE-NAME.xml`

**Describe alternatives you've considered**
We considered:
* Having one folder per `target` and keeping the same filename
* Having a section within the XML configuration files with a per `target` configuration overrides
* Having a section within the XML configuration files with a per `target` complete file override

**Tasks**
- [x] Design 
- [x] Implement in Engine
- [x] ~~Implement in Studio~~ (not needed for now)
- [x] ~~Implement in Deployer~~ (not needed for now)
- [x] Documentation
- [x] QA Testing

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/975
