### ISSUE TITLE
[studio] -Site Translation- Add locales to site-config and supporting API

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4019]
Add a section in `site-config.xml` to indicate available locales for this site and an API to _get_ these locales.

### Tasks
- [ ] Design and review a new section in `site-config.xml` that lists the available locales for this site
- [ ] Update UM to inject that into existing sites commented out (if missing, the system will work as it did)
- [ ] Add an API to retrieve the list of locales. Design and review before building.
