### ISSUE TITLE
-Site Translation- Render content based on locale tied to URL, cookie or browser locale

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4022]
Make Engine render site translations based on a cascading set of rules:
* URL/domain
* Cookie
* Browser locale
* Some other pluggable criteria
  * Allow the developer to specify rules for rendering primary and fallback languages and aligning that with the user (where the business can choose/override based on things like source IP/country, etc.)
  * We will provide the hooks, and the developer can override here and do things that fit the business need
    * User choice
    * Company choice
    * Filter/plugin resolves that into a viable return

### Tasks
- [x] Design mechanism and review it
- [x] Develop
  - [x] Locale resolvers (part of the url resolver was moved to https://github.com/craftercms/craftercms/issues/4168)
  - [x] Locale aware template loading
  - [x] Locale aware page rendering
- [ ] Test & validate
- [ ] Design & automate test cases
- [ ] Document

**Comment by jdrossl** [comment]
@sumerjabri @avasquez614 is this going to be integrated with existing classes or replace them completely? https://github.com/craftercms/engine/blob/master/src/main/java/org/craftercms/engine/targeting/impl/ConfigAwareCookieLocaleResolver.java

**Comment by jdrossl** [comment]
@sumerjabri @avasquez614 will components also support translation? if so what should happen with the references in the pages?

**Comment by jdrossl** [comment]
@sumerjabri @avasquez614 should we also support localized templates? something like https://freemarker.apache.org/docs/ref_directive_include.html#ref_directive_include_localized

**Comment by sumerjabri** [comment]
@jdrossl let's meet tomorrow and discuss. Initial reaction, yes!

**Comment by jdrossl** [comment]
@sumerjabri @avasquez614 we also have a default locale in `/config/engine/site-confix.xml` should we remove that one an use the one from studio instead?

**Comment by sumerjabri** [comment]
It'll be hard for users to set the default in two places. @avasquez614 what do you think?
