### ISSUE TITLE
[studio][studio-ui] - Site Policy - Implement basic Site Policies

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4354]
Please review the design document for full detail.

# Tasks
- [x] Review design and adjust as needed (ping me if anything is to change)
- [x] Design the APIs in OAS 3.0 and review them
- [x] Implement the backend services
  - [x] As REST and internal services
  - [x] As Java annotation to wrap the necessary services
- [x] Implement the frontend features
- [x] Document
- [ ] Test

**Comment by sumerjabri** [comment]
@jdrossl if BE is done, please assign to @rart for FE

**Comment by rart** [comment]
@aachavarria finish integration (from what I can gather, backend is merged?). **When done**, tick the "frontend features" checkbox on the ticket description and re-assign to vita.

**Comment by aachavarria** [comment]
The Site Policy was implemented to: Paste[cut/copy], Duplicate, Create Folder, Create Template, Create Script.
Please confirm if is missing another place.

**Comment by jdrossl** [comment]
@aachavarria Upload & Bulk upload?

**Comment by aachavarria** [comment]
Upload/Bulk Upload should use Action === 'CREATE'? @jdrossl

**Comment by jdrossl** [comment]
yeah

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1250

**Comment by yacdaniel** [comment]
Hi @jdrossl a couple of bugs:
1.  With Studio OOTB Site policy
2. , create a folder with over 255 chars, and put a file inside the folder,  now do a bulk upload of the folder to `Static-Assets`, example of the validate request
```
{"actions":[{
	"type":"CREATE",
	"target":"/static-assets/images/255_len_folder_gmpuhcqg9Jevy1LZ7It4YiH3oqgLeKZCU9DCCxWcokRWQ8un5rSnPjDxZBm9XWmTa8fvNMn2vcDYGQYKvzdGnZCffOtBtJWrBty42T5Mo7yaSZt1ro0d4sQxaseeqwYwlsOwRNnno3CoYDMsfy7YVmSvnM39rB8uoXmvMAYUbRbxhmdRhTIsOCKBuX36qcDkkhMcvznlkZbR1wJ6db8SI7pCEuCqdWP86L8HlGTqhpgG_end/foto1.png",
	"contentMetadata":{"fileSize":614}}]}
```
the response is item allowed
```
{"response":{"code":0,"message":"OK","remedialAction":"","documentationUrl":""},"results":[{"type":"CREATE","target":"/static-assets/images/255_len_folder_gmpuhcqg9Jevy1LZ7It4YiH3oqgLeKZCU9DCCxWcokRWQ8un5rSnPjDxZBm9XWmTa8fvNMn2vcDYGQYKvzdGnZCffOtBtJWrBty42T5Mo7yaSZt1ro0d4sQxaseeqwYwlsOwRNnno3CoYDMsfy7YVmSvnM39rB8uoXmvMAYUbRbxhmdRhTIsOCKBuX36qcDkkhMcvznlkZbR1wJ6db8SI7pCEuCqdWP86L8HlGTqhpgG_end/foto1.png","allowed":true,"modifiedValue":null}]}
```
but if fails to create the folder because of the validate now doesn't allow it. 
https://gist.github.com/yacdaniel/ad66dabe86db4ae85fb05761b749b5d2 

2. Setup a policy like below
```
    <!-- Only allow lowercase letters in the path -->
    <statement>
        <target-path-pattern>/static-assets/only-lowercase.*</target-path-pattern>
        <permitted>
            <path>
                <source-regex>([a-z\-/\.]*)</source-regex>
                <target-regex caseTransform="lowercase">$1</target-regex>
            </path>
        </permitted>
    </statement>
```
now upload an image with uppercase in the filename and accept the modification proposed by Site Policy. 
Looks like Studio is adding an extra `/` when the Policy proposal is accepted. 
```
commit 9fdc1ce1e1da9a7c46cc237a4fa38938ed60c87a (HEAD -> master)
Author: admin admin <evaladmin@example.com>
Date:   Thu Jul 29 14:46:03 2021 -0600
    User admin wrote content /static-assets/images/small//abcxyz.jpg
commit 74b3e302842f12c553dced26a46d3aafa1522a6b
```
https://gist.github.com/yacdaniel/9da6995cfb09fd394eff34de40444e98

3. I'm not able to setup list in the mime/content types, using a `,` is not working for me as the Site Policy sample indicates
```
                <mime-types/> (Comma separated list of MIME types, also support wildcards)

                <content-types/> (Comma separated list of content-types)
```

```
    <!-- Example: only allow images of less than 1 MB -->
    <statement>
        <target-path-pattern>/static-assets/images/.*</target-path-pattern>
        <permitted>
            <maximum-file-size>1000000</maximum-file-size>
            <mime-types>image/jpg,image/jpeg</mime-types>
        </permitted>
    </statement>
```

**Comment by jdrossl** [comment]
@rart for point 4 the UI needs to send the content-type in the metadata

**Comment by yacdaniel** [comment]
Verified in 4.0.
