### ISSUE TITLE
[studio-ui] Content types paths configuration don't match with items' path.

### ISSUE THREAD

**Issue by jvega190** [craftercms/craftercms#4473]
## Describe the bug

When calling the `/studio/api/1/services/api/1/content/get-content-types.json` service to get the allowed content types that can be created under a given path, it is not returning the correct content types for folders unless the path has a trailing slash (`/`).

It is the content type configuration that dictates this behaviour:
```xml
<paths>
	<includes>
		<pattern>^/site/components/articles-widget/.*</pattern>
	</includes>
</paths>
```

Notice that the `/` at the end is not optional on the regex (i.e. `/*` instead of `/?*`).

Paths don't include the trailing slash (rightfully so as it's not really a part of them). The issue is, the old UI code modifies the paths to include the slash whenever is a folder instead of simply honoring the item's path and allowing the config to work. We would like to avoid doing this on the new code but this could break old sites that have the expression (unnecessarily?) demanding the trailing slash.

### Tasks
- [ ] Make UpgradeManager update the configs
- [ ] Change config of all BPs
- [ ] Change legacy to blindly send the paths without altering per item type (folders)
- [ ] Make sure 4 has the same behaviour
- [ ] Test & validate all works properly/as expected
- [ ] Update docs if needed regarding the pattern (warnings, tips, etc)

## To Reproduce
1. Create a site based on editorial
2. Manually call `/studio/api/1/services/api/1/content/get-content-types.json?path=/site/taxonomy&site={sitename}`. Notice that the path is the same path the item retrieved by `/studio/api/1/services/api/1/content/get-items-tree.json` has (no '/' at the end).
3. See that no results are returned.
4. If a '/' is added at the end of the path in the URL, the expected results show up.

* In 3.1.x, the '/' is manually added so it can match the configuration set in the content-types.

## Expected behavior
The UI doesn't modify the path and configuration is simply honored.

### Version
Crafter 4.0.0-SNAPSHOT

**Comment by rart** [comment]
@russdanner any issue with going ahead with this? Ping me if you need clarification.

**Comment by sumerjabri** [comment]
@rart please add a `/` for 4.0.0 given everything else that requires BE work for 4.0.0.
Please abstract this into a path normalizer method which can be updated in a single place down the road and it will stop adding the `/`.

**Comment by russdanner** [comment]
Completed
