### ISSUE TITLE
[studio] Studio XML configuration is loaded in an inefficient manner wasting memory

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4510]
## Describe the bug
Memory allocation in Studio increases over time until GC runs and frees it. This is due to the non-caching of XML configuration.

## To Reproduce
1. Run Studio
2. Use a tool like VisualVM
3. See memory profile increase over time

## Expected behavior
XML configuration and other durable objects should be allocated once and cached until there is a need to invalidate. It's possible to use Guava to hold such objects.

## Tasks
- [x] Switch ConfigurationServiceImpl.java to leverage the configuration cache
- [x] Add ability to read configuration from the `global` repository with comparable methods to the ones that read the site configuration
- [x] Cache XML and YAML configuration being returned
- [x] Invalidate the cache if a config changes via Git (ping me)
~~Add HazelCast to signal cache invalidation across a cluster~~ cluster invalidation is handled via git too
- [x] Add a method to the interface and implementation to invalidate cache and wire it to write operations

## Screenshots
N/A

## Logs
N/A

### Version
4.0.0-SNAPSHOT (2/4/2021)

### OS
Ubuntu, Linux

### Browser
N/A

## Additional context
N/A

**Comment by sumerjabri** [comment]
Verified.
