### ISSUE TITLE
[studio][deployer] Create API to unlock Git

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4705]
**Is your feature request related to a problem? Please describe.**
There are situations where Git leaves an `index.lock` in `.git`. For example, shut down the process/machine while Git is working. This can leave the system incapable of proceeding without a manual delete of the lock.

**Describe the solution you'd like**
Add an API to remove the lock:

#### Studio
- Global: Required Role(s): Global Admin
- Sandbox (per site): Required Role(s): Global Admin or Site Admin
- Published (per site): Required Role(s): Global Admin or Site Admin

#### Deployer:
- Per site: Requires security token

### Tasks
- [x] Build for Studio and document via OAS
- [x] Build for Deployer
- [x] Document Deployer API in general docs
- [ ] Test

**Describe alternatives you've considered**

**Additional context**

**Comment by dejan-brkic** [comment]
Studio 3.1.x PR:
https://github.com/craftercms/studio/pull/2548

**Comment by dejan-brkic** [comment]
Studio 4.0 PR
https://github.com/craftercms/studio/pull/2552

**Comment by alhambrav** [comment]
Deployer unlock API: PR https://github.com/craftercms/docs/pull/1252 and https://github.com/craftercms/docs/pull/1253

**Comment by yacdaniel** [comment]
@jdrossl the enpoint `/api/1/target/unlock/:env/:site_name` is accepting any value in the `token` parameter.

Also @alhambrav we should add the parameter `token` to the docs, the default value for the token is the same as the monitoring tokens `defaultManagementToken`

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1277 and https://github.com/craftercms/docs/pull/1278

**Comment by yacdaniel** [comment]
@jdrossl peer our conversation, fix the unlock target in delivery.

**Comment by yacdaniel** [comment]
Verified fixed in `3.1.15-SNAPSHOT`

**Comment by yacdaniel** [comment]
Verified fixed in `4.0.0-SNAPSHOT`
