### ISSUE TITLE
[studio] Create Workflow Management API

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4720]
#### Feature
Create a new API set that:
- Retrieve the item state (bitmap) of items with pagination and filtering by:
  - path
  - bitmap
- Set or clear the following states (bulk operation against a list of items):
  - System Processing (clear)
  - Locked state (clear)
  - Publish: Live, Staging (set or clear)
- Set or clear the following states (bulk operation against a query result, provide the query and the action):
  - System Processing (clear)
  - Locked state (clear)
  - Publish: Live, Staging (set or clear)

#### Tasks
- [x] Design API in OAS and review (return a sandbox item (see OAS definition))
- [x] Build the backend services
- [x] Remove old APIs
- [x] Remove old API docs from Sphinx-Doc
- [x] Test and validate

**Comment by dejan-brkic** [comment]
PR:
https://github.com/craftercms/studio/pull/2591

**Comment by dejan-brkic** [comment]
@alhambrav These are services that need to be removed from docs:
https://docs.craftercms.org/en/4.0/developers/projects/studio/api/content/get-item-states.html
https://docs.craftercms.org/en/4.0/developers/projects/studio/api/content/set-item-state.html

**Comment by alhambrav** [comment]
PR https://github.com/craftercms/docs/pull/1290

**Comment by sumerjabri** [comment]
For "All States," you must send the state bitmap as all clear. The reason is that the flags are "AND" not "OR." Ping me if not clear.

**Comment by Euquimides** [comment]
Tested the workflow/item_states APIs product of this ticket. Issue #5372 surfaced during the test session and seems related with this API, please check it. Closing this ticket.
