### ISSUE TITLE
[studio-ui] Add a keyboard shortcut help section to the UI

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4777]
With PageBuilder's keyboard shortcuts, we should have a small help widget to show the keyboard shortcuts. Consider something small and unobtrusive.

`?` should bring up the keyboard shortcut help.

### Tasks
- [x] Build help widget
- [x] Add `?` to the keyboard shortcut list
- [x] Document the fact that we have keyboard shortcuts in the docs
  - `?` get help
- [x] Test and validate

**Comment by sumerjabri** [comment]
@yacdaniel FYI
