### ISSUE TITLE
[studio] Design and implement new dashboard APIs

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4815]
The existing dashboard APIs are limited in filtering, navigation and the objects returned.

We need new dashboard APIs:
- [ ] Define the required dashboards (from a business perspective)
- [ ] Design the UX
- [ ] Design the backing APIs and publish them as OAS
- [ ] Implement the backend
- [ ] Deprecate (disable really) the old APIs
- [ ] Update the UI
- [ ] Test
- [ ] Update the docs (screenshots, authoring guide, etc.)

**Comment by sumerjabri** [comment]
@dejan-brkic the publishing API shouldn't group by dates, let's have it just return paginated Packages. We will add another API to return the contents of a package as `sandbox` items. That way the API paginates correctly and meaningfully. @rart the second call to get the package contents can be rendered in a nice dialog to allow further filtering and actions to be taken by the user (normally users are looking at this dashboard to see the history of an item etc., I can explain more over a call).

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2890

**Comment by rart** [comment]
## Tasks

**Activity**
- Rename `action` to `actionType`
- Rename `item` to `target` (`target` becomes a variable container for the `targetType`)
- Add `targetType` (initial possible values are `"item"` or `"package"`)
- Remove `packageId` (as it would come on the `target` property — when `targetType` is `package`)
- When `targetType` is "_item_", target should have the following properties:
  - path
  - label
  - previewUrl
- Example:
```json
{
  "id": 5,
  "person": {
    "username": "admin",
    "firstName": "John",
    "lastName": "Admin",
    "avatar": "/blah.png"
  },
  "actionType": "UPDATE", 
  "actionTimestamp": "2022-03-28T19:51:58+02:00",
  "target": { path: "", label: "" },
  "targetType": "item"
}
```

**Scheduled**
- Throws when nothing to return
- Dates aren't marked required in Swagger
  - Update controller on too

**Pending**
- Throws when nothing to return

**Expiring**
- Throws
- Dates aren't marked required in Swagger
  - Update controller on too

**Expired**
- Throws (possibly due to lack of field expired_dt)

**Comment by rart** [comment]
@jdrossl please add parameter `activities` by activity to the /activity and /activity/me APIs. it should work in the same fashion as `usernames` (accept comma separated list of values)

**Comment by rart** [comment]
Issues & observations:
- [INFO] When creating a page, two entries are added
- [ERROR] When deleting a page, the CREATE entry item is no longer present hence all item props on the response is null

**Comment by sumerjabri** [comment]
1. This is a minor bug. This will be addressed when we refactor for bulk commits of actions. Let's meet and assess the impact on UX.
2. Can you work with this? Ultimately this will be fixed in https://github.com/craftercms/craftercms/issues/5369
3. Much of this will be fixed by https://github.com/craftercms/craftercms/issues/5244, however, we should meet and discussed what can be done in the near-term
4. Why? The service should return in reverse-chronological order with pagination. Let's meet and discuss.

**Comment by rart** [comment]
Please begin basic testing.
New site dashboard can be accesed via the usual dashboard popup but also directly via `/studio/site-dashboard`.

**Comment by sumerjabri** [comment]
@rart please update to work with files instead of packages for publishing concerns. Updates the API are expected, so make notes as needed.

**Comment by sumerjabri** [comment]
CC @jmendeza

**Comment by rart** [comment]
@jvega190 update blueprints and pass the ticket to sumer for UM work assignment.

**Comment by jvega190** [comment]
@sumerjabri PRs with bps updates are ready. Note that with the latest dashboard update it'll only be compatible with 4.1 (already updated in yaml file)

**Comment by sumerjabri** [comment]
@jmendeza please update UM

**Comment by jmendeza** [comment]
UM updated to add the new configs to ui.xml

**Comment by Euquimides** [comment]
Hi @jvega190 and @sumerjabri ! While testing the new Dashboard design, I noticed that there is no restriction to the `Authors` Username field, which allows to send a request to `GET /studio/api/2/users` with a massive keyword values. This will not be processed in the backend due to request size restrictions (which is an expected result).

Should we add a input size restriction for this text field as in other parts of Studio (Create User for example)?

**Comment by sumerjabri** [comment]
@Euquimides please create a separate ticket for the UI to restrict that field throughout.

**Comment by alhambrav** [comment]
Example update for dashboard images/text: https://docs.craftercms.org/en/4.1/by-role/author/author-screens.html#project-dashboard

**Comment by Euquimides** [comment]
Hi! Verified implementation of new Dashboards for Crafter v4.1. Will keep monitoring in case of any changes or issues that might arise. Thank you! Closing this ticket.
