### ISSUE TITLE
[studio] Add child-count to ChildrenBy API-set

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4866]
# Feature Request

#### Is your feature request related to a problem? Please describe.
The only way the UI knows to render or not render the `+` alongside containers/folders is to call the backend again to get the children.

#### Describe the solution you'd like
It would be better if the backend can return the number of children per item during the original ChildrenBy call.

#### Describe alternatives you've considered
N/A

#### Additional context
We should be mindful of performance implications.

## Tasks
- [x] Investigate the cost of this addition and share it with me
- [x] Design approach/query
- [x] Update the OAS docs
- [x] Implement
- [x] Test

**Comment by dejan-brkic** [comment]
This is the default static query (no filtering) for home page:
```
SELECT *, 0 as cnt FROM item WHERE site_id = 2 AND path = '/site/website/crafter-level-descriptor.level.xml'
        UNION
        (SELECT i1.*, count(1) as cnt FROM item i1 left outer join item i3 on i1.id = i3.parent_id WHERE i1.site_id = 2
        AND i1.path RLIKE('/site/website/[^/]+/index\.xml|/site/website/(?!index\.xml)[^/]+$')
        AND CONCAT(i1.path, '/index.xml') NOT IN
        (SELECT i2.path FROM item i2 WHERE i2.site_id = 2
        AND i2.path RLIKE('/site/website/[^/]+/index\.xml'))
        AND i1.path NOT LIKE '%/crafter-level-descriptor.level.xml'
        AND i1.ignored = 0
        and (i3.ignored = 0 or i3.ignored is null)
        AND (i3.path NOT LIKE '%/crafter-level-descriptor.level.xml' or i3.path is null)
        group by i1.id
        LIMIT 0,10) ;
```

The performance cost is around 10% (40ms vs 44ms)

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2688

**Comment by sumerjabri** [comment]
@rart validate you're getting the count and switch the UI to use it
@yacdaniel add to API automation testing

**Comment by rart** [comment]
`item_by_path` is returning very high numbers that don't match — as far as I can see — anything.

For example `/site/website/index.xml` has 6 children but the service returns 31536
<img width="177" alt="image" src="https://user-images.githubusercontent.com/3928341/128430395-d6d3ade1-6bf4-407a-acb1-2a748ac16000.png">

`/templates/web` has 4 but returns 10512
<img width="178" alt="image" src="https://user-images.githubusercontent.com/3928341/128430225-f50d9af4-82a1-4325-8281-677dc3203933.png">

...and so on.

`children_by_path` looks correct.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2696

**Comment by rart** [comment]
- `/site/website/` returns as below (i.e. trailing slash breaks it)
```
{
  "response": { ... },
  "item": null
}
```

- `/site/website` returns childrenCount of `0` (i.e. only works for `/index.xml` terminated paths)

- `/site/website/articles` only has 2 children but returns 3. It may be counting the level descriptor or some hidden files?

All tests were on OOTB editorial bp.

**Comment by dejan-brkic** [comment]
* We don't support trailing slash
* `parent-child` relationship is defined as a child having reference to the parent. In that sense, it supports only one parent and it is always content preferred
* level descriptors are counted as children. That decision was made after the initial implementation as level descriptors are actually descendants and in the corner case of a folder (or page) with a level descriptor and no other subfolders or files, that level descriptor will actually never be displayed since children count will be zero. For details you can talk with @sumerjabri

**Comment by sumerjabri** [comment]
@Euquimides please add to the automation test suite

**Comment by Euquimides** [comment]
Hi! Updated and tested the APIs. Proceeding to add them to the automation suite, ticket #5382.
