### ISSUE TITLE
[studio] Add start_stop_publisher permission to the system and all BPs

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4868]
Add the new permission to the system, all BPs, and update UM to include in existing installations.

### Tasks
- [x] Add the permission to the docs
- [x] Add to the BE
- [ ] Add to the UI where applicable
- [x] Add to all BPs
- [x] Add to UM

**Comment by sumerjabri** [comment]
Done
