### ISSUE TITLE
[studio] Update Publishing Status API

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4870]
### Tasks
- [x] Remove the `message` field from the site publishing status in the database and API response
- [x] Add the number of files being published
- [x] Add the number of files currently published so we can create a progress bar
- [x] Update the UI to have a localized message that's formatted based on the returned JSON

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2707

**Comment by sumerjabri** [comment]
@rart we would like to start with a localized status and get to a progress bar based on this. I would consider a 1 or 2-pixel blue line progressing left to right just below the top nav if that's possible or similar ideas.

**Comment by rart** [comment]
@aachavarria ping me to review design when you get to this ticket.

**Comment by rart** [comment]
@sumerjabri, as discussed, there are some discrepancies in the docs vs actual response.

- Docs show a submitter & dateSubmitted field that the API response doesn't contain
- Actual api response contains an `environment` prop
  - Should be named `target` (or `publishingTarget`, but given this is publishing status api target sounds fair)
  - Docs don't reflect this field

**Comment by sumerjabri** [comment]
@dejan-brkic we can discuss this ticket when you're ready to work on it.

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2755

renamed `environment` to `publishingTarget`
`submitter` and `dateSubmitted` fields removed. There can be multiple submitters for one package and date submitted is not tracked

**Comment by rart** [comment]
@jvega190 please apply following changes:

- Colour becomes binary (green vs red)
  - if enabled, color = green, else, color = red     
- Display a localized message based on response.status
  - ready: "Ready."
  - processing: "Preparing items for publishing."
  - publishing: "Publishing: published {numberOfItems} items out of {totalItems} to {publishingTarget}. Package id is {submissionId}."
  - queued: "Items are scheduled for publishing."
  - stopped: "The publisher was stopped by an administrator."
  - error: "The publisher was stopped due to an error."

**Comment by sumerjabri** [comment]
@dejan-brkic please:
* move the workflow/delete to be content/delete
* remove the workflow/delete from docs
* update controllers

**Comment by jvega190** [comment]
Backend issues verified fixed
