### ISSUE TITLE
[studio] Add a publishing submission type (user, system)

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4871]
We need to track whether an item is being published because of a direct user request (user) or a system including the file (dep-calc). There might be 2 types of system requests: required dep or optional dep with user choice to include.

Please add that into the database and APIs and use it for future reporting (new Dashboard).

### Tasks
- [ ] Design the database
- [ ] Identify APIs to be updated (the UI must indicate optional dep-calc)
- [ ] Identify UI components to be updated
- [ ] Update OAS
- [ ] Implement BE
- [ ] Implement UI
- [ ] Test

Required for https://github.com/craftercms/craftercms/issues/4815

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2731
