### ISSUE TITLE
[studio-ui] Create CDATA configuration block

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4874]
We must figure out what elements require CDATA escaping. To that end, we must have a configuration block that lists element regexes indicating which elements must be CDATA escaped.

Our initial list is:
- `_html`, `_t`, `_s`, `_smv`, `_mvs`
- `internal-name`

@rart please propose a configuration file that can be read easily by PB and the existing Form Engine.

### Tasks
- [x] Identify the configuration file
- [x] Design the configuration format
- [x] Implement in PB
- [x] Implement in FE
- [x] Update the existing BPs (built-in and MP)
- [x] Update UM
- [x] Test
- [x] Document how to use this feature

**Comment by jvega190** [comment]
This can be tested now, marketplace bps are pending for publishing.
