### ISSUE TITLE
[studio] Publish site uuid as part of API calls

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#4898]
# Feature Request

#### Is your feature request related to a problem? Please describe.
The uuid has various characteristics that make specially useful. Please include that piece of information on all the site objects across different API calls.

#### Describe the solution you'd like
Please include that piece of information on all the site objects across different API calls.

#### Tasks
- [x] https://app.swaggerhub.com/apis/craftercms/studio/4.0.0.20#/Site
- [x] https://app.swaggerhub.com/apis/craftercms/studio/4.0.0.20#/users/getUserSites
- [x] https://app.swaggerhub.com/apis/craftercms/studio/4.0.0.20#/users/getCurrentUserSites
- [x] https://docs.craftercms.org/en/3.1/developers/projects/studio/api/site/create-site.html
- [x] https://docs.craftercms.org/en/3.1/developers/projects/studio/api/site/get-site.html
- [x] https://docs.craftercms.org/en/3.1/developers/projects/studio/api/site/get-sites-per-user.html <== seems to have it but please double check it's the right value
- [x] https://app.swaggerhub.com/apis/craftercms/studio/4.0.0.20#/Site <== update site model

#### Describe alternatives you've considered
{{A clear and concise description of any alternative solutions or features you've considered.}}

#### Additional context
https://app.swaggerhub.com/apis/craftercms/studio/4.0.0.20#/Site the site model seems to be outdated on our docs as we also have name now.

**Comment by sumerjabri** [comment]
@dejan-brkic please also update the site model is OAS

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2686

@alhambrav Please update docs for 3.1 APIs (not checked) by adding `siteUuid` and `name` properties for response object

**Comment by alhambrav** [comment]
The https://docs.craftercms.org/en/3.1/developers/projects/studio/api/site/create-site.html does not need an update because it does not have a response object, only a message for the response.  Marking that task as done.

**Comment by rart** [comment]
Verified
