### ISSUE TITLE
[plugin][chatbot] Create a chatbot plugin to allow authors to add a chatbot to pages/sections

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4923]
Repository: https://github.com/craftercms/chatbot-plugin

Consider using the inheritance system overridable by page for enablement/disablement of the chatbot on pages.

Start with a good design and a simple implementation with room to grow.

Please add templates for:
- [x] Collect.chat
- [x] Cliengo
- [x] Tidio
- [x] LivePerson
- [x] LiveChat
- [x] Quiq
- [x] LiveAgent
- [x] HubSpot Service Hub
- [x] Userlike
- [x] Olark
- [x] FreshDesk

### Tasks
- [x] Research chatbots vendors and decide what we will support
- [x] Design
- [x] Implement BE
- [x] Implement FE (not required, the chatbot FE is handled by the providers)
- [x] Test
- [x] Document in README.md within the plugin
- [x] Publish to the Marketplace

**Comment by sumerjabri** [comment]
@jdrossl please refactor the plugins per the new configuration mechanics. Additionally, please simplify the documentation to have a single listing of the configuration required and clearly indicate which file to edit/use.

**Comment by sumerjabri** [comment]
Please update all readmes (including the `master` readme) to match what we have now.

**Comment by jdrossl** [comment]
Doc updates covered as part of https://github.com/craftercms/craftercms/issues/5224
