### ISSUE TITLE
[studio-ui] Switch 3.1.x sites to run within Next UI

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4924]
3.1.x sites run within the legacy UI application. We would like to switch that to run within the new Next UI and move the legacy app to a different URL space in preparation for eventual retirement.

### Tasks
- [x] Research the viability of this approach and consider having a legacy host bridge, some updates to the ICE tools and hiding of unused rools, and remember the UM is available to help with config
- [x] Estimate the effort and communicate that to @sumerjabri 
- [x] Design
- [x] Implement
- [x] Update UM default `ui.xml` file to be 3.1 compatibility file
- [x] Test
- [x] Document insofar as indicating in the release notes what will change and how can developers fully upgrade 3.1.x sites to 4.0 and Page Builder (related to Page Builder documentation)

**Comment by sumerjabri** [comment]
@alhambrav I can think of 3 things at least:
* Update `ui.xml` to get the same Sidebar you're used to
* Update your Elasticsearch code to match the latest Elasticsearch changes, we can ask @jdrossl for links to ES and other resources or write our own article to simplify
* Update ICE to move to XB (if desired), and point to the XB article

**Comment by alhambrav** [comment]
Updates added to release notes breaking changes section: https://github.com/craftercms/docs/pull/1455/commits/57c1d46e664a73f4ffc7c7a421033fd3ddbd85d7
