### ISSUE TITLE
[plugin][social-media-widgets] Create a Social Media Widgets plugin

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4926]
Repo: https://github.com/craftercms/social-media-plugin

Requirements:
* Allow authors to create a widget with social media links and place it on pages
* The widget will show the social media network logo along with a link to said network

Consider having a preset widget with the basic logos and links to the network (not to a brand) to get started quickly.

Start with a good design and a simple implementation with room to grow.

### Tasks
- [x] Design
- [x] Implement BE
- [x] Implement FE
- [x] Test
- [x] Document in README.md within the plugin
- [x] Publish to the Marketplace

**Comment by sumerjabri** [comment]
Issues:
- [ ] Add a thumbnail image:
![image](https://user-images.githubusercontent.com/3931908/153938980-900e123c-e32e-4d5f-98f0-270ce14380d6.png)
- [ ] Images render at various sizes when the component is rendered (should there be a width property?):
![image](https://user-images.githubusercontent.com/3931908/153939101-d65bd1ff-abad-4163-9926-9616100979fb.png)
- [ ] Links from the SM should open in a new tab
- [ ] There is no attached data source to allow the user to upload from their system (please add that)
- [ ] Make clear that the image/icon is optional, and if none are provided, the system will use the built-in version
![image](https://user-images.githubusercontent.com/3931908/153939367-3ed807eb-a88c-4bf9-a887-6735fa9c8e91.png)

**Comment by jvega190** [comment]
@sumerjabri please let me know if you still see the icons dimension issue on the current plugin version

**Comment by jvega190** [comment]
Icon dimensions working properly after latest update
