### ISSUE TITLE
[studio] Add upgrade entry point from 3.1.x to 4.0.x

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#4993]
#### Is your feature request related to a problem? Please describe.
Add a new entry point to upgrade from the list below to 4.0.0:
- 3.1.9
- 3.1.12
- 3.1.13
- 3.1.17
- 3.1.18

##### Tasks
- [x] Upgrade repositories
- [x] Upgrade database
- [x] Test and validate
- [x] Document that you may upgrade to 4.0.0.x via these starting points

**Comment by jdrossl** [comment]
@yacdaniel @alhambrav we need to document that this upgrade requires this env variable to be increased depending on the size of the existing sites. In my tests I had to increase it 3x the default.

https://github.com/craftercms/craftercms/blob/develop/resources/env/authoring/bin/crafter-setenv.sh#L85

**Comment by yacdaniel** [comment]
Hi @jdrossl please take a look to these issues found so far:
- [ ]  `.keep` files should be removed during upgrade.
- [ ] `lockowner` should be set to clear when item isn't locked. 
- [ ] `start-upgrade.sh` is not taking into account the new 4.0 bundle name( from `crafter` to `crafter-authoring`) same issue in `delivery`
```
./upgrade.sh 
./upgrade.sh: line 29: cd: /opt/crafter/3117/crafter/temp/upgrade/crafter: No such file or directory
./upgrade.sh: line 33: /bin/upgrade/upgrade-target.sh: No such file or directory
ls /opt/crafter/3117/crafter/temp/upgrade/       
crafter-authoring  upgrade.sh
```

**Comment by jdrossl** [comment]
@yacdaniel all fixes are merged now

**Comment by alhambrav** [comment]
Docs - commit https://github.com/craftercms/docs/pull/1383/commits/2e51140a860f6c238df6d29e1de5d8f95cb9696b

**Comment by yacdaniel** [comment]
Hi @jdrossl please take a look to the next issue:
- upgrade from 3.1.9 to 4.0 fails https://gist.github.com/yacdaniel/a302c280d1135892847609beeed0f2a8

**Comment by yacdaniel** [comment]
@jdrossl please take a look to the upgrade of control `rte-tinymce5` 3.1 to `rte` 4.0, when the control is inside a repeating group.

![image](https://user-images.githubusercontent.com/6722074/148254941-6515e990-f51c-47d9-996b-fd090106c5ba.png)

**Comment by yacdaniel** [comment]
Verified fixed. 
![image](https://user-images.githubusercontent.com/6722074/148442619-abbab018-10f8-4d92-9845-3840ccafad2a.png)
