### ISSUE TITLE
[deployer] Make processors declare which mode they execute within (reindex, publish, ...)

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5046]
#### Is your feature request related to a problem? Please describe.
Reindexing causes all processors to execute, even if not related to reindexing, causing problems like duplicate emails, multiple insertions into external DBs, etc.

#### Describe the solution you'd like
When the deployer executes the processors, it's best to declare the mode it is in. Modes suggested are:
* Publish (regular publish)
* Search Reindex (reprocess content for the purpose of updating the search index)

Additional modes can be added for emerging use-cases.

##### Tasks
- [x] Update the API to allow for deployment from a certain point and to set the mode
- [x] Update the processors to run in all modes and Search in Search Reindex mode
- [x] Research if the "point" can be a date/time or just commit ID (date-time is desirable and timezone must be figured out)
- [x] Review design
- [x] Implement

#### Describe alternatives you've considered
Having the API accept the list of processors to execute. Rejected because that knowledge leads to data duplication and the need to sync the processor list and the code/external knowledge.

**Comment by yacdaniel** [comment]
Verified fixed.
