### ISSUE TITLE
[studio][engine] Unify plugin configuration

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5123]
#### Is your feature request related to a problem? Please describe.
Today there is no common mechanism for adding configuration to Studio and Engine plugins.

#### Tasks
- [ ] Add plugins folder to config (auth and delivery) with `plugin.xml` using a `plugin-id` based path.

```
/config/plugins/{plugin-id}/plugin.xml
```

The plugin can retrieve its configuration via simple API and dot notation (like Engine site config).

- [ ] Add plugin configuration API
- [ ] Update the Plugin Manager to allow edit of the XML on the Plugin Management UI

**Comment by russdanner** [comment]
Confirmed
