### ISSUE TITLE
[studio-ui] Add feedback to the user upon performing long operations

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5173]
#### Crafter CMS Version
4.0.0-SNAPSHOT

#### Date of Build
2021/12/22

#### Describe the bug
Some operations take a long time and the user is not getting a visual indicator that the system is working on their request.

#### To Reproduce
* Copy a large tree
* Bulk publish
* Paste something big

### Tasks
- [x] Add spinner/similar to Bulk Publish and disable the publish button once started
- [x] Add spinner/similar to copy (cut?)
- [x] Add spinner/similar to paste
- [ ] Investigate other similar operations and see what else needs the same

#### Logs
N/A

#### Screenshots
N/A

**Comment by rart** [comment]
@yacdaniel any ideas of other places with the same issue?

**Comment by sumerjabri** [comment]
@rart no spinner on:
* `Paste` operation
* `Cut` operation (maybe too fast?)

**Comment by rart** [comment]
Look at the bottom right. We use a little floating message. Maybe too subtle but we would need to come up with an alternative otherwise. I didn't want to block the UI.

**Comment by sumerjabri** [comment]
@rart please lock the UI. Ping me for details if required.
