### ISSUE TITLE
[studio][studio-ui] Bulk publish on first publish

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5207]
#### Is your feature request related to a problem? Please describe.
The first publishing of a site can lead to issues without an initial bulk publish of the entire site.

#### Describe the solution you'd like
Make bulk publishing a recommended operation upon a first publish operation.

##### Tasks
- [x] #5262
- [x] [studio-ui] The publishing dialog(s) will check the above API, if a site has never been published the dialog will show "The entire site will be published along with this publish request since this is the very first publish."
- [x] [studio-ui] The dialog for approval/rejection will show the same warning for the reviewer
- [x] [studio-ui] The dialog will not show dependencies/packages/individual files in this case
- [x] [studio-ui] Update the publishing targets retrieval service to use `/publish/available_targets`
- [x] [studio] Studio publishing system will detect that the site has never been published before and therefore bulk publish (clone/etc) the entire sandbox the first time regardless of any other consideration
- [x] [docs] Remove API v1 `get-available-publishing-channels` service [https://docs.craftercms.org/en/4.0/developers/projects/studio/api/deployment/get-available-publishing-channels.html](url)
- [x] [studio] Deprecate / Remove API v1 `get-available-publishing-channels` service

#### Describe alternatives you've considered
Publish on create.
Allow/disallow bulk publish on first publish.

**Comment by dejan-brkic** [comment]
BE Done
PR:
https://github.com/craftercms/studio/pull/2829

**Comment by aachavarria** [comment]
Doing testing, im still having issues with an Author

**Comment by aachavarria** [comment]
Im still having issues

**Comment by sumerjabri** [comment]
@dejan-brkic please address the last bullet

**Comment by dejan-brkic** [comment]
Done
PR:
https://github.com/craftercms/studio/pull/2874
