### ISSUE TITLE
[studio] Update eventbus and propagate events to the UI via a Websocket

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5325]
### Tasks
- [ ] Design the new event bus, spec out the tech, the event catalog, and other details
- [ ] Update Studio's event bus tech to the new tech
- [ ] Update all existing events and rewire as needed
- [ ] Implement the server-side WebSocket
- [ ] Implement the WebSocket bridge filter
- [ ] Handoff to UI

**Comment by rart** [comment]
@jdrossl please allow CORs on the websocket so we don't disrupt UI development and maintain the API-first capabilities

**Comment by rart** [comment]
@jvega190 TODOs:

- [ ] Test socket disconnection/reconnection
- [ ] Implement events from socket
- [ ] Clean previous set of events the UI implemented virtually that the backend tackled differently
- [ ] Kill path & tree nav polling

(Will/Let's keep this list updated as we identify further tasks)
