### ISSUE TITLE
[studio] Design and implement a Recycle Bin

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5369]
#### Is your feature request related to a problem? Please describe.
Deletion today, while reversible, can be made better with a recycle bin.

#### Describe the solution you'd like
See the design doc.

#### Tasks
- [ ] Review and update the design document
- [ ] Update the OAS API spec
- [ ] Implement the back end
- [ ] Design and review the UI
- [ ] Implement the frontend
- [ ] Test
- [ ] Document
