### ISSUE TITLE
[studio] CORS option to set origin with a regex

### ISSUE THREAD

**Issue by phuongnq** [craftercms/craftercms#5381]
### Feature Request

Add an option to the CORS configuration to accept a regex.

#### Is your feature request related to a problem? Please describe.

Without regex, users need to list all values to configure CORS origin

#### Describe the solution you'd like

Add `setAllowedOriginPatterns` option to enable a general regex while configuring CORS.

#### Tasks
- [x] Implement the above
- [x] Configure with a basic configuration that works for local installs easily (already done?)
- [x] Test
- [x] Document how to configure this
- [x] Document how to secure this in the Secure your CrafterCMS Installation guide as needed
- [x] Document this in the release notes

https://docs.spring.io/spring-framework/docs/5.3.13/javadoc-api/org/springframework/web/cors/CorsConfiguration.html#setAllowedOriginPatterns-java.util.List-

#### Describe alternatives you've considered
N/A

**Comment by phuongnq** [comment]
Partly verified. All patterns are working as expected but this one: 

```
https://*.domain1.com:[8080,8081] -- domains ending with domain1.com on port 8080 or port 8081
```
Seem like because of the comma `,` usage.

![cor](https://user-images.githubusercontent.com/2996543/166852146-c694270a-ec1a-4382-9d4b-f966837814f7.png)
![setting](https://user-images.githubusercontent.com/2996543/166852191-687f330a-f8d8-4549-b538-672e24605421.png)

**Comment by jdrossl** [comment]
hey @phuongnq , for Engine all commas need to be escaped `\,` (see the other properties) otherwise it will be split and CORS will get an incomplete value

**Comment by jdrossl** [comment]
Because we need to split values using `,` and the new pattern can include the character we will need to escape the inner one:

```
http://localhost:[8000\,3000],http://other.domain
```

This applies to all modules: studio, engine, social, profile

We will need to add a note about this in the documentation

**Comment by phuongnq** [comment]
Verified. Thank you!
