### ISSUE TITLE
[all] Upgrade to Elasticsearch 8

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5406]
Upgrade all modules to Elasticsearch 8

##### Tasks
- [ ] Evaluate ES8 and see what it means to upgrade
- [ ] Test the upgrade against our blueprints and some sites
- [ ] Make a decision to upgrade to ES8 or not
- [ ] Upgrade to ES8 (if the decision is to upgrade)

**Comment by jdrossl** [comment]
The following issues are present with ES 8.1.1:
- The RHLC has been removed:
  - All sites need to migrate to the new client and we lose backward compatibility with 3.1.x
  - The issue with the create index mentioned [here](https://github.com/craftercms/craftercms/issues/5274) has not been fixed yet
- We need to test for breaking changes, not possible right now because of the previous issue

**Comment by sumerjabri** [comment]
Switched to OpenSearch
