### ISSUE TITLE
[studio-ui] Improve deployment target status indicators value

### ISSUE THREAD

**Issue by russdanner** [craftercms/craftercms#5442]
#### Is your feature request related to a problem? Please describe.
The current implementation of deployment target status indicators shows when an item has reached a deployment target (Staging and Live) for the **first** time. Therefore, once set, they do not provide additional value on later edits (and thus become irrelevant.)
<img width="942" alt="Screen Shot 2022-04-05 at 2 49 38 PM" src="https://user-images.githubusercontent.com/169432/161830826-97868007-f602-45f7-8751-f9b8642d40f4.png">

<img width="307" alt="Screen Shot 2022-04-05 at 3 11 05 PM" src="https://user-images.githubusercontent.com/169432/161833472-d81483e3-64d3-406c-a340-11b41ada6155.png">

We want to improve them so that they reset after an edit and thus track the progress of an edit to staging or live deployment targets.

#### Describe the solution you'd like
Reset the indicators of a given item for both Staging and Live after an edit. Set the indicator ON as the edit makes it to each target. 

#### Describe alternatives you've considered
{{A clear and concise description of any alternative solutions or features you've considered.}}

#### Tasks

- [x] Remove indicators form all locations (Sidebar, Main Nav, Dashboard) -- v4.0.0 [UI work only]
- [ ] #5462

**Comment by sumerjabri** [comment]
Please update the UI's context menu of items:
- [ ] Hide the state for folders
- [ ] If an item is not in any workflow, then show the publishing state
Sidebar updates:
- [ ] For non-folders, the white circle will be set to publishing state when an item is not in workflow
