### ISSUE TITLE
[studio] Hide unused configuration files via UM

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5523]
#### Is your feature request related to a problem? Please describe.
There are configuration files that are no longer in use, we should hide them in 4.0.0 and ultimately delete them

#### Tasks
Hide from the configuration editor via UM by removing these files from the list of configurations.
- [x] Preview Panel Config
- [x] Preview Component Config
- [x] Targetting Config
- [x] Sidebar Config
- [x] Code Editor Config
- [x] Rename `Project Config Tools` to `Content Type Editor Config`
- [x] Update the BPs
- [x] Document the above (@alhambrav )

Update the blueprints and built-in sites to delete the above list of files.

If possible, delete the files in 4.0-based sites and hide them from 3.1-based sites. The file Preview Component Config must stay for 3.1-based sites.

#### Describe alternatives you've considered
Use UM to delete the files outright.
