### ISSUE TITLE
[studio][studio-ui] Content types can be overridden by creating a new one with the same ID

### ISSUE THREAD

**Issue by rart** [craftercms/craftercms#5801]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

If you attempt to create a type with an existing id, without warning you'll override the previous type

### Tasks
- [x] [UI] Disallow the creation of a content type if the ID is already in use
- [ ] [BE] Fail the creation of a content type if that content type already exists

### Steps to reproduce

Steps:

1. Go to project tools > content types
2. Click on new type and create a type with a certain id (add a field or two to make the issue more evident)
3. Go back to the list page and create another type with the same id
4. See the issue

**Comment by phuongnq** [comment]
@sumerjabri 
When creating a new Content-Type, we actually perform several calls to the API: `/studio/api/2/configuration/write_configuration` to create the following files:

```
config.xml
controller.groovy
form-definition.xml
```
The API implementation does not separate the action create/edit and it will update the file accordingly with whatever we have in the payload (https://github.com/craftercms/studio/blob/develop/src/main/java/org/craftercms/studio/impl/v2/service/configuration/ConfigurationServiceImpl.java#L354).
For that reason, I belive these is no further update required for the backend.
