### ISSUE TITLE
[deployer] Authoring search is using Jacket indexing for binary indexing

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5815]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

Even though jacket indexing includes binary indexing, it was not meant to be used by Authoring Search. A new class is needed to properly index binaries in Authoring. Ping @avasquez614 for more information.

### Tasks
- [ ] Design the solution [Alfonso]
- [ ] Implement [Phil]
- [ ] Test
- [ ] Document any updates

**Comment by sumerjabri** [comment]
Duplicates https://github.com/craftersoftware/craftercms/issues/425
