### ISSUE TITLE
[studio-ui][studio] Switch to using `zxcvbn` for password strength management

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#5816]
### Duplicates

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Presently, Studio enforces password strength by length, mix-case, and numeric character minimums. This is not necessarily a good way to judge a password's strength.

### Describe the solution you'd like

Switch the UI and backend to use https://github.com/dropbox/zxcvbn. We can accept a minimum of X (configurable) where X is the `score` value of the estimator with a default of 4.

#### Tasks
- [x] UI switch to using the new library and use the params/config injected via FTL
- [x] Backend switch to using the new library's Java bindings and drive the configuration based on `studio-config.yaml` param `studio.security.passwordRequirements.minimumComplexity`. Remember: set password, reset password, create user, etc.

Work will be done in the branch: https://github.com/craftercms/studio/pull/new/feature/5816

**Comment by rart** [comment]
![PasswordComplexityUI](https://user-images.githubusercontent.com/3928341/207893603-fd64f499-a4f3-48ac-91fe-af5db971f999.png)

**Comment by yacdaniel** [comment]
Verified fixed.
![image](https://user-images.githubusercontent.com/6722074/212718106-fa381f08-f012-4737-b5f1-de904b2873be.png)
