### ISSUE TITLE
[studio] Remove Git commits from the database where possible

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#6126]
### Latest version

- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

As we move away from having the GitLog table and keeping DB and Git synced from a commit log perspective, it's time to remove Git commit IDs from the system where possible.

### Tasks
- Review all tables that carry a commit ID
- Remove the commit IDs where possible
- Try to remove it from the site table (last synced if possible)
