### ISSUE TITLE
[core] Create a SkipAll processor that can skips the item processing pipeline

### ISSUE THREAD

**Issue by sumerjabri** [craftercms/craftercms#6184]
### Latest version

- [ ] The issue is in the latest released 4.2.x
- [X] The issue is in the latest released 4.1.x
- [X] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Duplicates

- [X] I have searched the existing issues

### Is your enhancement request related to a problem? Please describe.

In certain circumstances, it's desirable to get an item without any processing and to skip the default processing pipeline entirely.

### Tasks
* Add a new `isExclusive` boolean to the `ItemProcessor` interface with a default `false`
* When performing getItem with an explicit processor passed in, check if the processor is exclusive, if so, process this processor only without anything else in the pipeline
* Create a new `SkipAllItemProcessor` that has `exclusive` set to `true` and does nothing (No Op)

The above allows a developer to call `getSiteItem(URL, SkipAllItemProcessor)` which will get the item as-is without processing it.
